/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: LlamaDDS.h
  Source: /mnt/e/TI/git/llama.cpp_dds/dds/idl/LlamaDDS.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_LLAMADDS_H_CA76383CD67C4654A35CDB6B582E9C7F
#define DDSC_LLAMADDS_H_CA76383CD67C4654A35CDB6B582E9C7F

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct llama_ChatMessage
{
  char * role;
  char * content;
} llama_ChatMessage;

extern const dds_topic_descriptor_t llama_ChatMessage_desc;

#define llama_ChatMessage__alloc() \
((llama_ChatMessage*) dds_alloc (sizeof (llama_ChatMessage)));

#define llama_ChatMessage_free(d,o) \
dds_sample_free ((d), &llama_ChatMessage_desc, (o))

#ifndef DDS_SEQUENCE_LLAMA_CHATMESSAGE_DEFINED
#define DDS_SEQUENCE_LLAMA_CHATMESSAGE_DEFINED
typedef struct dds_sequence_llama_ChatMessage
{
  uint32_t _maximum;
  uint32_t _length;
  struct llama_ChatMessage *_buffer;
  bool _release;
} dds_sequence_llama_ChatMessage;

#define dds_sequence_llama_ChatMessage__alloc() \
((dds_sequence_llama_ChatMessage*) dds_alloc (sizeof (dds_sequence_llama_ChatMessage)));

#define dds_sequence_llama_ChatMessage_allocbuf(l) \
((struct llama_ChatMessage *) dds_alloc ((l) * sizeof (struct llama_ChatMessage)))
#endif /* DDS_SEQUENCE_LLAMA_CHATMESSAGE_DEFINED */

#ifndef DDS_SEQUENCE_FLOAT_DEFINED
#define DDS_SEQUENCE_FLOAT_DEFINED
typedef struct dds_sequence_float
{
  uint32_t _maximum;
  uint32_t _length;
  float *_buffer;
  bool _release;
} dds_sequence_float;

#define dds_sequence_float__alloc() \
((dds_sequence_float*) dds_alloc (sizeof (dds_sequence_float)));

#define dds_sequence_float_allocbuf(l) \
((float *) dds_alloc ((l) * sizeof (float)))
#endif /* DDS_SEQUENCE_FLOAT_DEFINED */

#ifndef DDS_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} dds_sequence_long;

#define dds_sequence_long__alloc() \
((dds_sequence_long*) dds_alloc (sizeof (dds_sequence_long)));

#define dds_sequence_long_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
#endif /* DDS_SEQUENCE_LONG_DEFINED */

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

typedef struct llama_ChatCompletionRequest
{
  char * request_id;
  char * model;
  dds_sequence_llama_ChatMessage messages;
  float temperature;
  int32_t max_tokens;
  bool stream;
  dds_sequence_float top_p;
  dds_sequence_long n;
  dds_sequence_string stop;
} llama_ChatCompletionRequest;

extern const dds_topic_descriptor_t llama_ChatCompletionRequest_desc;

#define llama_ChatCompletionRequest__alloc() \
((llama_ChatCompletionRequest*) dds_alloc (sizeof (llama_ChatCompletionRequest)));

#define llama_ChatCompletionRequest_free(d,o) \
dds_sample_free ((d), &llama_ChatCompletionRequest_desc, (o))

typedef struct llama_ChatCompletionResponse
{
  char * request_id;
  char * model;
  char * content;
  char * finish_reason;
  bool is_final;
  int32_t prompt_tokens;
  int32_t completion_tokens;
} llama_ChatCompletionResponse;

extern const dds_topic_descriptor_t llama_ChatCompletionResponse_desc;

#define llama_ChatCompletionResponse__alloc() \
((llama_ChatCompletionResponse*) dds_alloc (sizeof (llama_ChatCompletionResponse)));

#define llama_ChatCompletionResponse_free(d,o) \
dds_sample_free ((d), &llama_ChatCompletionResponse_desc, (o))

typedef struct llama_ServerStatus
{
  char * server_id;
  int32_t slots_idle;
  int32_t slots_processing;
  char * model_loaded;
  bool ready;
} llama_ServerStatus;

extern const dds_topic_descriptor_t llama_ServerStatus_desc;

#define llama_ServerStatus__alloc() \
((llama_ServerStatus*) dds_alloc (sizeof (llama_ServerStatus)));

#define llama_ServerStatus_free(d,o) \
dds_sample_free ((d), &llama_ServerStatus_desc, (o))

typedef struct llama_EmbeddingRequest
{
  char * request_id;
  char * model;
  char * input;
} llama_EmbeddingRequest;

extern const dds_topic_descriptor_t llama_EmbeddingRequest_desc;

#define llama_EmbeddingRequest__alloc() \
((llama_EmbeddingRequest*) dds_alloc (sizeof (llama_EmbeddingRequest)));

#define llama_EmbeddingRequest_free(d,o) \
dds_sample_free ((d), &llama_EmbeddingRequest_desc, (o))

#ifndef DDS_SEQUENCE_FLOAT_DEFINED
#define DDS_SEQUENCE_FLOAT_DEFINED
typedef struct dds_sequence_float
{
  uint32_t _maximum;
  uint32_t _length;
  float *_buffer;
  bool _release;
} dds_sequence_float;

#define dds_sequence_float__alloc() \
((dds_sequence_float*) dds_alloc (sizeof (dds_sequence_float)));

#define dds_sequence_float_allocbuf(l) \
((float *) dds_alloc ((l) * sizeof (float)))
#endif /* DDS_SEQUENCE_FLOAT_DEFINED */

typedef struct llama_EmbeddingResponse
{
  char * request_id;
  char * model;
  dds_sequence_float embedding;
  int32_t tokens;
} llama_EmbeddingResponse;

extern const dds_topic_descriptor_t llama_EmbeddingResponse_desc;

#define llama_EmbeddingResponse__alloc() \
((llama_EmbeddingResponse*) dds_alloc (sizeof (llama_EmbeddingResponse)));

#define llama_EmbeddingResponse_free(d,o) \
dds_sample_free ((d), &llama_EmbeddingResponse_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_LLAMADDS_H_CA76383CD67C4654A35CDB6B582E9C7F */
