/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: OrchestratorDDS.h
  Source: /run/host/var/mnt/HD1TB/tese/src/llama_cpp/dds/idl/OrchestratorDDS.idl
  Cyclone DDS: V11.0.1

*****************************************************************/
#ifndef DDSC_ORCHESTRATORDDS_H_748AE850CA93961B6ED95BDBAEEAAD13
#define DDSC_ORCHESTRATORDDS_H_748AE850CA93961B6ED95BDBAEEAAD13

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct orchestrator_LLMInferenceRequest
{
  char * request_id;
  char * task_id;
  char * agent_id;
  char * model_name;
  char * messages_json;
  float temperature;
  uint32_t max_tokens;
  bool stream;
  int32_t security_level;
  char * provider_constraint;
  uint64_t created_at_ns;
} orchestrator_LLMInferenceRequest;

extern const dds_topic_descriptor_t orchestrator_LLMInferenceRequest_desc;

#define orchestrator_LLMInferenceRequest__alloc() \
((orchestrator_LLMInferenceRequest*) dds_alloc (sizeof (orchestrator_LLMInferenceRequest)));

#define orchestrator_LLMInferenceRequest_free(d,o) \
dds_sample_free ((d), &orchestrator_LLMInferenceRequest_desc, (o))

typedef struct orchestrator_LLMInferenceResult
{
  char * request_id;
  uint32_t seq_num;
  char * content;
  bool is_final;
  int32_t finish_reason;
  char * model_used;
  uint32_t tokens_prompt;
  uint32_t tokens_completion;
  uint64_t emitted_at_ns;
} orchestrator_LLMInferenceResult;

extern const dds_topic_descriptor_t orchestrator_LLMInferenceResult_desc;

#define orchestrator_LLMInferenceResult__alloc() \
((orchestrator_LLMInferenceResult*) dds_alloc (sizeof (orchestrator_LLMInferenceResult)));

#define orchestrator_LLMInferenceResult_free(d,o) \
dds_sample_free ((d), &orchestrator_LLMInferenceResult_desc, (o))

typedef struct orchestrator_LLMInferenceError
{
  char * request_id;
  int32_t error_code;
  char * error_message;
  char * provider;
  bool retriable;
  uint64_t emitted_at_ns;
} orchestrator_LLMInferenceError;

extern const dds_topic_descriptor_t orchestrator_LLMInferenceError_desc;

#define orchestrator_LLMInferenceError__alloc() \
((orchestrator_LLMInferenceError*) dds_alloc (sizeof (orchestrator_LLMInferenceError)));

#define orchestrator_LLMInferenceError_free(d,o) \
dds_sample_free ((d), &orchestrator_LLMInferenceError_desc, (o))

typedef struct orchestrator_ServerStatus
{
  char * server_id;
  int32_t slots_idle;
  int32_t slots_processing;
  char * model_loaded;
  bool ready;
} orchestrator_ServerStatus;

extern const dds_topic_descriptor_t orchestrator_ServerStatus_desc;

#define orchestrator_ServerStatus__alloc() \
((orchestrator_ServerStatus*) dds_alloc (sizeof (orchestrator_ServerStatus)));

#define orchestrator_ServerStatus_free(d,o) \
dds_sample_free ((d), &orchestrator_ServerStatus_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ORCHESTRATORDDS_H_748AE850CA93961B6ED95BDBAEEAAD13 */
