"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.0
  Module: orchestrator
  IDL file: OrchestratorDDS.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import orchestrator


@dataclass
@annotate.final
@annotate.autoid("sequential")
class AgentRegistration(idl.IdlStruct, typename="orchestrator.AgentRegistration"):
    agent_id: str
    hostname: str
    port: types.int32
    model: str
    model_path: str
    vram_available_mb: types.int32
    vram_total_mb: types.int32
    slots_idle: types.int32
    slots_total: types.int32
    vision_enabled: bool
    reasoning_enabled: bool
    registered_at: types.int32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class AgentStatus(idl.IdlStruct, typename="orchestrator.AgentStatus"):
    agent_id: str
    state: str
    current_slots: types.int32
    idle_slots: types.int32
    memory_usage_mb: types.int32
    vram_usage_mb: types.int32
    current_model: str
    last_heartbeat: types.int32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class TaskRequest(idl.IdlStruct, typename="orchestrator.TaskRequest"):
    task_id: str
    requester_id: str
    task_type: str
    messages_json: str
    priority: types.int32
    timeout_ms: types.int32
    requires_context: bool
    context_id: str
    created_at: types.int32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class TaskResponse(idl.IdlStruct, typename="orchestrator.TaskResponse"):
    task_id: str
    agent_id: str
    content: str
    is_final: bool
    prompt_tokens: types.int32
    completion_tokens: types.int32
    processing_time_ms: types.int32
    success: bool
    error_message: str
    created_at: types.int32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class ClientRequest(idl.IdlStruct, typename="orchestrator.ClientRequest"):
    request_id: str
    client_id: str
    task_type: str
    messages_json: str
    priority: types.int32
    timeout_ms: types.int32
    requires_context: bool


@dataclass
@annotate.final
@annotate.autoid("sequential")
class ClientResponse(idl.IdlStruct, typename="orchestrator.ClientResponse"):
    request_id: str
    content: str
    is_final: bool
    prompt_tokens: types.int32
    completion_tokens: types.int32
    processing_time_ms: types.int32
    success: bool
    error_message: str


