/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: OrchestratorV4.h
  Source: /run/host/var/mnt/HD1TB/tese/src/llama_cpp/dds/v4/idl/OrchestratorV4.idl
  Cyclone DDS: V11.0.1

*****************************************************************/
#ifndef DDSC_ORCHESTRATORV4_H_B015546E461A38638F88776972835545
#define DDSC_ORCHESTRATORV4_H_B015546E461A38638F88776972835545

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum dds_llm_orchestrator_TaskStatus
{
  dds_llm_orchestrator_TS_PENDING,
  dds_llm_orchestrator_TS_ASSIGNED,
  dds_llm_orchestrator_TS_RUNNING,
  dds_llm_orchestrator_TS_DONE,
  dds_llm_orchestrator_TS_FAILED
} dds_llm_orchestrator_TaskStatus;

#define dds_llm_orchestrator_TaskStatus__alloc() \
((dds_llm_orchestrator_TaskStatus*) dds_alloc (sizeof (dds_llm_orchestrator_TaskStatus)));

typedef enum dds_llm_orchestrator_TaskPriority
{
  dds_llm_orchestrator_TP_LOW,
  dds_llm_orchestrator_TP_NORMAL,
  dds_llm_orchestrator_TP_HIGH
} dds_llm_orchestrator_TaskPriority;

#define dds_llm_orchestrator_TaskPriority__alloc() \
((dds_llm_orchestrator_TaskPriority*) dds_alloc (sizeof (dds_llm_orchestrator_TaskPriority)));

typedef enum dds_llm_orchestrator_ModelSpecialization
{
  dds_llm_orchestrator_MS_TEXT,
  dds_llm_orchestrator_MS_VISION,
  dds_llm_orchestrator_MS_EMBEDDING
} dds_llm_orchestrator_ModelSpecialization;

#define dds_llm_orchestrator_ModelSpecialization__alloc() \
((dds_llm_orchestrator_ModelSpecialization*) dds_alloc (sizeof (dds_llm_orchestrator_ModelSpecialization)));

typedef struct dds_llm_orchestrator_Task
{
  char * task_id;
  char * client_id;
  char * assigned_agent;
  char * target_agent;
  int32_t model_required;
  char * model_name;
  char * messages_json;
  float temperature;
  uint32_t max_tokens;
  bool stream;
  int32_t status;
  int32_t priority;
  uint64_t created_at_ns;
  uint64_t assigned_at_ns;
  uint64_t started_at_ns;
  uint64_t completed_at_ns;
  uint64_t deadline_ns;
  uint32_t retry_count;
  char * finish_reason;
  uint64_t t_serialization_ns;
  uint64_t t_transport_send_ns;
  uint64_t t_agent_queue_ns;
  uint64_t t_inference_ns;
  uint64_t t_transport_return_ns;
  uint64_t t_deserialization_ns;
} dds_llm_orchestrator_Task;

extern const dds_topic_descriptor_t dds_llm_orchestrator_Task_desc;

#define dds_llm_orchestrator_Task__alloc() \
((dds_llm_orchestrator_Task*) dds_alloc (sizeof (dds_llm_orchestrator_Task)));

#define dds_llm_orchestrator_Task_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_Task_desc, (o))

typedef enum dds_llm_orchestrator_AgentHealth
{
  dds_llm_orchestrator_AH_OFFLINE,
  dds_llm_orchestrator_AH_DEGRADED,
  dds_llm_orchestrator_AH_HEALTHY
} dds_llm_orchestrator_AgentHealth;

#define dds_llm_orchestrator_AgentHealth__alloc() \
((dds_llm_orchestrator_AgentHealth*) dds_alloc (sizeof (dds_llm_orchestrator_AgentHealth)));

typedef struct dds_llm_orchestrator_AgentState
{
  char * agent_id;
  char * hostname;
  char * model;
  char * specialization;
  uint32_t slots_total;
  uint32_t slots_busy;
  uint32_t vram_total_mb;
  uint32_t vram_used_mb;
  float ema_latency_ms;
  uint32_t completed_total;
  uint32_t failed_total;
  int32_t health;
  uint64_t last_update_ns;
  uint64_t uptime_seconds;
} dds_llm_orchestrator_AgentState;

extern const dds_topic_descriptor_t dds_llm_orchestrator_AgentState_desc;

#define dds_llm_orchestrator_AgentState__alloc() \
((dds_llm_orchestrator_AgentState*) dds_alloc (sizeof (dds_llm_orchestrator_AgentState)));

#define dds_llm_orchestrator_AgentState_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_AgentState_desc, (o))

typedef enum dds_llm_orchestrator_FinishReason
{
  dds_llm_orchestrator_FR_NONE,
  dds_llm_orchestrator_FR_COMPLETION,
  dds_llm_orchestrator_FR_LENGTH,
  dds_llm_orchestrator_FR_TIMEOUT,
  dds_llm_orchestrator_FR_ERROR
} dds_llm_orchestrator_FinishReason;

#define dds_llm_orchestrator_FinishReason__alloc() \
((dds_llm_orchestrator_FinishReason*) dds_alloc (sizeof (dds_llm_orchestrator_FinishReason)));

typedef struct dds_llm_orchestrator_TaskOutput
{
  char * task_id;
  uint32_t seq_num;
  char * content;
  bool is_final;
  int32_t finish_reason;
  char * agent_id;
  uint32_t token_count;
  uint64_t emitted_at_ns;
} dds_llm_orchestrator_TaskOutput;

extern const dds_topic_descriptor_t dds_llm_orchestrator_TaskOutput_desc;

#define dds_llm_orchestrator_TaskOutput__alloc() \
((dds_llm_orchestrator_TaskOutput*) dds_alloc (sizeof (dds_llm_orchestrator_TaskOutput)));

#define dds_llm_orchestrator_TaskOutput_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_TaskOutput_desc, (o))

typedef enum dds_llm_orchestrator_ComponentType
{
  dds_llm_orchestrator_CT_ORCHESTRATOR,
  dds_llm_orchestrator_CT_AGENT,
  dds_llm_orchestrator_CT_LLAMA_SERVER,
  dds_llm_orchestrator_CT_CLIENT
} dds_llm_orchestrator_ComponentType;

#define dds_llm_orchestrator_ComponentType__alloc() \
((dds_llm_orchestrator_ComponentType*) dds_alloc (sizeof (dds_llm_orchestrator_ComponentType)));

typedef struct dds_llm_orchestrator_SystemMetric
{
  char * metric_name;
  char * component_id;
  int32_t component_type;
  float value;
  char * unit;
  uint64_t timestamp_ns;
} dds_llm_orchestrator_SystemMetric;

extern const dds_topic_descriptor_t dds_llm_orchestrator_SystemMetric_desc;

#define dds_llm_orchestrator_SystemMetric__alloc() \
((dds_llm_orchestrator_SystemMetric*) dds_alloc (sizeof (dds_llm_orchestrator_SystemMetric)));

#define dds_llm_orchestrator_SystemMetric_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_SystemMetric_desc, (o))

typedef struct dds_llm_orchestrator_QoSRoutingProfile
{
  char * profile_id;
  int32_t version;
  char * profile_name;
  char * preferred_agent_prefix;
  char * allowed_agent_prefixes_json;
  char * weights_json;
  int32_t fallback_after_ms;
  float centroid_score;
  char * explanation_json;
  uint64_t timestamp_ns;
} dds_llm_orchestrator_QoSRoutingProfile;

extern const dds_topic_descriptor_t dds_llm_orchestrator_QoSRoutingProfile_desc;

#define dds_llm_orchestrator_QoSRoutingProfile__alloc() \
((dds_llm_orchestrator_QoSRoutingProfile*) dds_alloc (sizeof (dds_llm_orchestrator_QoSRoutingProfile)));

#define dds_llm_orchestrator_QoSRoutingProfile_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_QoSRoutingProfile_desc, (o))

typedef struct dds_llm_orchestrator_ContextSnapshot
{
  char * context_id;
  char * client_id;
  char * session_id;
  char * messages_json;
  char * metadata_json;
  int32_t security_level;
  uint64_t created_at_ns;
  uint64_t updated_at_ns;
  uint32_t ttl_seconds;
} dds_llm_orchestrator_ContextSnapshot;

extern const dds_topic_descriptor_t dds_llm_orchestrator_ContextSnapshot_desc;

#define dds_llm_orchestrator_ContextSnapshot__alloc() \
((dds_llm_orchestrator_ContextSnapshot*) dds_alloc (sizeof (dds_llm_orchestrator_ContextSnapshot)));

#define dds_llm_orchestrator_ContextSnapshot_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_ContextSnapshot_desc, (o))

typedef struct dds_llm_orchestrator_ContextUpdate
{
  char * context_id;
  int32_t update_type;
  char * messages_delta_json;
  char * metadata_delta_json;
  uint64_t updated_at_ns;
} dds_llm_orchestrator_ContextUpdate;

extern const dds_topic_descriptor_t dds_llm_orchestrator_ContextUpdate_desc;

#define dds_llm_orchestrator_ContextUpdate__alloc() \
((dds_llm_orchestrator_ContextUpdate*) dds_alloc (sizeof (dds_llm_orchestrator_ContextUpdate)));

#define dds_llm_orchestrator_ContextUpdate_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_ContextUpdate_desc, (o))

typedef struct dds_llm_orchestrator_ToolCallRequest
{
  char * call_id;
  char * request_id;
  char * tool_name;
  char * arguments_json;
  int32_t security_level;
  int32_t status;
  char * result_json;
  char * error_message;
  uint64_t created_at_ns;
  uint64_t completed_at_ns;
} dds_llm_orchestrator_ToolCallRequest;

extern const dds_topic_descriptor_t dds_llm_orchestrator_ToolCallRequest_desc;

#define dds_llm_orchestrator_ToolCallRequest__alloc() \
((dds_llm_orchestrator_ToolCallRequest*) dds_alloc (sizeof (dds_llm_orchestrator_ToolCallRequest)));

#define dds_llm_orchestrator_ToolCallRequest_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_ToolCallRequest_desc, (o))

typedef struct dds_llm_orchestrator_ExecutionTraceEvent
{
  char * trace_id;
  uint32_t seq_num;
  int32_t event_type;
  char * task_id;
  char * request_id;
  char * agent_id;
  char * component_id;
  int32_t component_type;
  char * payload_json;
  uint64_t timestamp_ns;
} dds_llm_orchestrator_ExecutionTraceEvent;

extern const dds_topic_descriptor_t dds_llm_orchestrator_ExecutionTraceEvent_desc;

#define dds_llm_orchestrator_ExecutionTraceEvent__alloc() \
((dds_llm_orchestrator_ExecutionTraceEvent*) dds_alloc (sizeof (dds_llm_orchestrator_ExecutionTraceEvent)));

#define dds_llm_orchestrator_ExecutionTraceEvent_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_ExecutionTraceEvent_desc, (o))

typedef struct dds_llm_orchestrator_SecurityPolicySnapshot
{
  char * policy_id;
  int32_t version;
  char * policy_json;
  char * published_by;
  uint64_t timestamp_ns;
} dds_llm_orchestrator_SecurityPolicySnapshot;

extern const dds_topic_descriptor_t dds_llm_orchestrator_SecurityPolicySnapshot_desc;

#define dds_llm_orchestrator_SecurityPolicySnapshot__alloc() \
((dds_llm_orchestrator_SecurityPolicySnapshot*) dds_alloc (sizeof (dds_llm_orchestrator_SecurityPolicySnapshot)));

#define dds_llm_orchestrator_SecurityPolicySnapshot_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_SecurityPolicySnapshot_desc, (o))

typedef struct dds_llm_orchestrator_SecurityPolicyUpdate
{
  char * policy_id;
  int32_t previous_version;
  int32_t new_version;
  char * operation;
  char * rule_delta_json;
  char * published_by;
  uint64_t timestamp_ns;
} dds_llm_orchestrator_SecurityPolicyUpdate;

extern const dds_topic_descriptor_t dds_llm_orchestrator_SecurityPolicyUpdate_desc;

#define dds_llm_orchestrator_SecurityPolicyUpdate__alloc() \
((dds_llm_orchestrator_SecurityPolicyUpdate*) dds_alloc (sizeof (dds_llm_orchestrator_SecurityPolicyUpdate)));

#define dds_llm_orchestrator_SecurityPolicyUpdate_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_SecurityPolicyUpdate_desc, (o))

typedef struct dds_llm_orchestrator_QoSMetric
{
  char * metric_id;
  char * metric_name;
  char * component;
  int64_t value;
  int32_t delta;
  int32_t window_ms;
  uint64_t timestamp_ns;
  char * experiment_id;
  char * run_id;
  char * qos_profile;
  char * load_level;
  char * network_condition;
  char * payload_level;
  int32_t replication_idx;
  bool warmup;
} dds_llm_orchestrator_QoSMetric;

extern const dds_topic_descriptor_t dds_llm_orchestrator_QoSMetric_desc;

#define dds_llm_orchestrator_QoSMetric__alloc() \
((dds_llm_orchestrator_QoSMetric*) dds_alloc (sizeof (dds_llm_orchestrator_QoSMetric)));

#define dds_llm_orchestrator_QoSMetric_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_QoSMetric_desc, (o))

typedef struct dds_llm_orchestrator_QoSViolation
{
  char * violation_id;
  char * violation_type;
  char * topic_name;
  char * component;
  char * entity_kind;
  char * affected_entity;
  char * severity;
  char * details_json;
  uint64_t timestamp_ns;
  char * experiment_id;
  char * run_id;
  char * qos_profile;
  char * load_level;
  char * network_condition;
  char * payload_level;
  int32_t replication_idx;
  bool warmup;
} dds_llm_orchestrator_QoSViolation;

extern const dds_topic_descriptor_t dds_llm_orchestrator_QoSViolation_desc;

#define dds_llm_orchestrator_QoSViolation__alloc() \
((dds_llm_orchestrator_QoSViolation*) dds_alloc (sizeof (dds_llm_orchestrator_QoSViolation)));

#define dds_llm_orchestrator_QoSViolation_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_QoSViolation_desc, (o))

typedef struct dds_llm_orchestrator_DiscoveryEvent
{
  char * event_id;
  char * event_type;
  char * topic_name;
  char * local_entity;
  char * remote_entity;
  int32_t count_change;
  uint64_t timestamp_ns;
} dds_llm_orchestrator_DiscoveryEvent;

extern const dds_topic_descriptor_t dds_llm_orchestrator_DiscoveryEvent_desc;

#define dds_llm_orchestrator_DiscoveryEvent__alloc() \
((dds_llm_orchestrator_DiscoveryEvent*) dds_alloc (sizeof (dds_llm_orchestrator_DiscoveryEvent)));

#define dds_llm_orchestrator_DiscoveryEvent_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_DiscoveryEvent_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ORCHESTRATORV4_H_B015546E461A38638F88776972835545 */
