/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: OrchestratorV4.h
  Source: /Users/zeitune/Documents/tese/llama.cpp_dds/dds/v4/idl/OrchestratorV4.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_ORCHESTRATORV4_H_BFF6AF889C3F43AE3672EE97C5059494
#define DDSC_ORCHESTRATORV4_H_BFF6AF889C3F43AE3672EE97C5059494

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum dds_llm_orchestrator_TaskStatus
{
  dds_llm_orchestrator_TS_PENDING,
  dds_llm_orchestrator_TS_ASSIGNED,
  dds_llm_orchestrator_TS_RUNNING,
  dds_llm_orchestrator_TS_DONE,
  dds_llm_orchestrator_TS_FAILED
} dds_llm_orchestrator_TaskStatus;

#define dds_llm_orchestrator_TaskStatus__alloc() \
((dds_llm_orchestrator_TaskStatus*) dds_alloc (sizeof (dds_llm_orchestrator_TaskStatus)));

typedef enum dds_llm_orchestrator_TaskPriority
{
  dds_llm_orchestrator_TP_LOW,
  dds_llm_orchestrator_TP_NORMAL,
  dds_llm_orchestrator_TP_HIGH
} dds_llm_orchestrator_TaskPriority;

#define dds_llm_orchestrator_TaskPriority__alloc() \
((dds_llm_orchestrator_TaskPriority*) dds_alloc (sizeof (dds_llm_orchestrator_TaskPriority)));

typedef enum dds_llm_orchestrator_ModelSpecialization
{
  dds_llm_orchestrator_MS_TEXT,
  dds_llm_orchestrator_MS_VISION,
  dds_llm_orchestrator_MS_EMBEDDING
} dds_llm_orchestrator_ModelSpecialization;

#define dds_llm_orchestrator_ModelSpecialization__alloc() \
((dds_llm_orchestrator_ModelSpecialization*) dds_alloc (sizeof (dds_llm_orchestrator_ModelSpecialization)));

typedef struct dds_llm_orchestrator_Task
{
  char * task_id;
  char * client_id;
  char * assigned_agent;
  int32_t model_required;
  char * model_name;
  char * messages_json;
  float temperature;
  uint32_t max_tokens;
  bool stream;
  int32_t status;
  int32_t priority;
  uint64_t created_at_ns;
  uint64_t assigned_at_ns;
  uint64_t started_at_ns;
  uint64_t completed_at_ns;
  uint64_t deadline_ns;
  uint32_t retry_count;
  char * finish_reason;
} dds_llm_orchestrator_Task;

extern const dds_topic_descriptor_t dds_llm_orchestrator_Task_desc;

#define dds_llm_orchestrator_Task__alloc() \
((dds_llm_orchestrator_Task*) dds_alloc (sizeof (dds_llm_orchestrator_Task)));

#define dds_llm_orchestrator_Task_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_Task_desc, (o))

typedef enum dds_llm_orchestrator_AgentHealth
{
  dds_llm_orchestrator_AH_OFFLINE,
  dds_llm_orchestrator_AH_DEGRADED,
  dds_llm_orchestrator_AH_HEALTHY
} dds_llm_orchestrator_AgentHealth;

#define dds_llm_orchestrator_AgentHealth__alloc() \
((dds_llm_orchestrator_AgentHealth*) dds_alloc (sizeof (dds_llm_orchestrator_AgentHealth)));

typedef struct dds_llm_orchestrator_AgentState
{
  char * agent_id;
  char * hostname;
  char * model;
  char * specialization;
  uint32_t slots_total;
  uint32_t slots_busy;
  uint32_t vram_total_mb;
  uint32_t vram_used_mb;
  float ema_latency_ms;
  uint32_t completed_total;
  uint32_t failed_total;
  int32_t health;
  uint64_t last_update_ns;
  uint64_t uptime_seconds;
} dds_llm_orchestrator_AgentState;

extern const dds_topic_descriptor_t dds_llm_orchestrator_AgentState_desc;

#define dds_llm_orchestrator_AgentState__alloc() \
((dds_llm_orchestrator_AgentState*) dds_alloc (sizeof (dds_llm_orchestrator_AgentState)));

#define dds_llm_orchestrator_AgentState_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_AgentState_desc, (o))

typedef enum dds_llm_orchestrator_FinishReason
{
  dds_llm_orchestrator_FR_NONE,
  dds_llm_orchestrator_FR_COMPLETION,
  dds_llm_orchestrator_FR_LENGTH,
  dds_llm_orchestrator_FR_TIMEOUT,
  dds_llm_orchestrator_FR_ERROR
} dds_llm_orchestrator_FinishReason;

#define dds_llm_orchestrator_FinishReason__alloc() \
((dds_llm_orchestrator_FinishReason*) dds_alloc (sizeof (dds_llm_orchestrator_FinishReason)));

typedef struct dds_llm_orchestrator_TaskOutput
{
  char * task_id;
  uint32_t seq_num;
  char * content;
  bool is_final;
  int32_t finish_reason;
  uint64_t emitted_at_ns;
} dds_llm_orchestrator_TaskOutput;

extern const dds_topic_descriptor_t dds_llm_orchestrator_TaskOutput_desc;

#define dds_llm_orchestrator_TaskOutput__alloc() \
((dds_llm_orchestrator_TaskOutput*) dds_alloc (sizeof (dds_llm_orchestrator_TaskOutput)));

#define dds_llm_orchestrator_TaskOutput_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_TaskOutput_desc, (o))

typedef enum dds_llm_orchestrator_ComponentType
{
  dds_llm_orchestrator_CT_ORCHESTRATOR,
  dds_llm_orchestrator_CT_AGENT,
  dds_llm_orchestrator_CT_LLAMA_SERVER,
  dds_llm_orchestrator_CT_CLIENT
} dds_llm_orchestrator_ComponentType;

#define dds_llm_orchestrator_ComponentType__alloc() \
((dds_llm_orchestrator_ComponentType*) dds_alloc (sizeof (dds_llm_orchestrator_ComponentType)));

typedef struct dds_llm_orchestrator_SystemMetric
{
  char * metric_name;
  char * component_id;
  int32_t component_type;
  double value;
  char * unit;
  uint64_t timestamp_ns;
} dds_llm_orchestrator_SystemMetric;

extern const dds_topic_descriptor_t dds_llm_orchestrator_SystemMetric_desc;

#define dds_llm_orchestrator_SystemMetric__alloc() \
((dds_llm_orchestrator_SystemMetric*) dds_alloc (sizeof (dds_llm_orchestrator_SystemMetric)));

#define dds_llm_orchestrator_SystemMetric_free(d,o) \
dds_sample_free ((d), &dds_llm_orchestrator_SystemMetric_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ORCHESTRATORV4_H_BFF6AF889C3F43AE3672EE97C5059494 */
